### ISSUE TITLE
An error appears when I input "python3 -m nrpy.examples.wave_equation_cartesian".

### ISSUE THREAD

**Issue by wc1018** [nrpy/nrpy#22]
When I have downloaded nrpy through pip in cmd, then an error happens after I input  "python -m nrpy.examples.wave_equation_cartesian".

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\Anaconda3_2309\Lib\site-packages\nrpy\examples\wave_equation_cartesian.py", line 438, in <module>
    register_CFunction_exact_solution_single_Cartesian_point()
  File "D:\Anaconda3_2309\Lib\site-packages\nrpy\examples\wave_equation_cartesian.py", line 187, in register_CFunction_exact_solution_single_Cartesian_point
    cfc.register_CFunction(
  File "D:\Anaconda3_2309\Lib\site-packages\nrpy\c_function.py", line 274, in register_CFunction
    CFunction_dict[actual_name] = CFunction(
                                  ^^^^^^^^^^
  File "D:\Anaconda3_2309\Lib\site-packages\nrpy\c_function.py", line 101, in __init__
    self.raw_function, self.full_function = self.generate_full_function()
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda3_2309\Lib\site-packages\nrpy\c_function.py", line 198, in generate_full_function
    return complete_func, clang_format(
                          ^^^^^^^^^^^^^
  File "D:\Anaconda3_2309\Lib\site-packages\nrpy\helpers\generic.py", line 80, in clang_format
    with subprocess.Popen(
         ^^^^^^^^^^^^^^^^^
  File "D:\Anaconda3_2309\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\Anaconda3_2309\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by zachetienne** [comment]
Hello! It appears that you do not have `clang-format` installed, which is used by NRPy to consistently format the C code that is output. I believe that this may fix the problem:

```
conda install -c conda-forge clang-format
```
